from xlb.operator.boundary_condition.boundary_condition import BoundaryCondition
from xlb.operator.boundary_condition.full_bounce_back import FullBounceBack
from xlb.operator.boundary_condition.halfway_bounce_back import HalfwayBounceBack
